# Generated by Django 2.2.1 on 2019-05-12 00:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_contact_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('groceries', 'Grocery'), ('officesupplies', 'Officesupplies'), ('party', 'Party')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('info', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
