# Generated by Django 2.2.1 on 2019-05-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190511_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('groceries', 'Grocery'), ('officesupplies', 'OfficeSupplies'), ('party', 'Party'), ('party', 'Party')], max_length=50),
        ),
    ]
