# Generated by Django 2.2.1 on 2019-05-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190511_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('groceries', 'Grocery'), ('officesupplies', 'OfficeSupplies'), ('party', 'Party')], max_length=50),
        ),
    ]
