# Generated by Django 2.2.1 on 2019-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190512_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
