# Generated by Django 2.2.1 on 2019-05-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('groceries', 'Grocery'), ('officesupplies', 'OfficeSupplies'), ('party', 'Party'), ('tool', 'tools'), ('other', 'Other')], max_length=50),
        ),
    ]
